namespace ThreeAppGen.Services;

/// <summary>A starting point for a generated application.</summary>
public sealed record ProjectTemplate(
    string Id,
    string Title,
    string Category,
    string Description,
    string ProgramCode,
    bool UsesAvalonia = false);

/// <summary>
/// The catalogue offered by "New project - From template". Every template
/// produces a project that builds and runs as is.
/// </summary>
public static class ProjectTemplates
{
    public static ProjectTemplate? Find(string id) =>
        All.FirstOrDefault(template => string.Equals(template.Id, id, StringComparison.OrdinalIgnoreCase));

    public static IReadOnlyList<ProjectTemplate> All { get; } =
    [
        new ProjectTemplate(
            "blank",
            "Blank window",
            "Basics",
            "An empty scene with a camera, one light and the render loop wired up.",
            """
            // Generated by Three.Net App Generator (Jack - The Code Bender).
            // Made with Three.Net by Gravicode Studios - led by Kang Fadhil.

            using System.Numerics;
            using ThreeNet;

            using Scene scene = new()
            {
                Environment = SceneEnvironment.Default with { Background = MathHelpers.FromHex(0x0B0D12) },
            };

            Node sun = scene.AddLight(Light.Directional(Vector3.One, 3f), name: "sun");
            sun.Position = new Vector3(4f, 6f, 4f);
            sun.LookAt(Vector3.Zero);

            Node camera = scene.AddCamera(Camera.Perspective(55f.ToRadians()), new Vector3(0f, 2f, 6f));
            camera.LookAt(Vector3.Zero);

            AppWindow window = new(WindowOptions.Default with { Title = "Three.Net app" });
            window.Load += renderer => Console.WriteLine($"GPU: {renderer.AdapterName}");
            window.Render += (renderer, delta) => renderer.Render(scene, camera);
            window.Run();
            """),

        new ProjectTemplate(
            "spinning-cube",
            "Spinning cube",
            "Basics",
            "A lit PBR cube on a ground plane, rotating every frame.",
            """
            // Generated by Three.Net App Generator (Jack - The Code Bender).

            using System.Numerics;
            using ThreeNet;

            using Scene scene = new()
            {
                Environment = SceneEnvironment.Default with { AmbientIntensity = 0.12f },
            };

            Material cubeMaterial = scene.CreateMaterial(MaterialOptions.Pbr(Colors.Orange, metallic: 0.1f, roughness: 0.35f));
            Node cube = scene.AddMesh(scene.CreateBoxGeometry(1.4f, 1.4f, 1.4f), cubeMaterial, name: "cube");
            cube.Position = new Vector3(0f, 0.7f, 0f);

            Material floorMaterial = scene.CreateMaterial(MaterialOptions.Pbr(Colors.Gray, 0f, 0.9f));
            Node floor = scene.AddMesh(scene.CreatePlaneGeometry(30f, 30f), floorMaterial, name: "floor");
            floor.EulerAngles = new Vector3(-MathF.PI / 2f, 0f, 0f);

            Node sun = scene.AddLight(Light.Directional(Vector3.One, 3.2f));
            sun.Position = new Vector3(5f, 7f, 5f);
            sun.LookAt(Vector3.Zero);

            Node camera = scene.AddCamera(Camera.Perspective(55f.ToRadians()), new Vector3(0f, 2.5f, 6f));
            camera.LookAt(new Vector3(0f, 0.7f, 0f));

            float elapsed = 0f;
            AppWindow window = new(WindowOptions.Default with { Title = "Spinning cube" });
            window.Render += (renderer, delta) =>
            {
                elapsed += delta;
                cube.EulerAngles = new Vector3(elapsed * 0.6f, elapsed, 0f);
                renderer.Render(scene, camera);
            };
            window.Run();
            """),

        new ProjectTemplate(
            "solar-system",
            "Solar system",
            "Animation",
            "Nested pivots driving planets and moons: the scene graph doing the maths.",
            """
            // Generated by Three.Net App Generator (Jack - The Code Bender).

            using System.Numerics;
            using ThreeNet;

            using Scene scene = new()
            {
                Environment = SceneEnvironment.Default with
                {
                    Background = MathHelpers.FromHex(0x05060B),
                    AmbientIntensity = 0.02f,
                },
            };

            Geometry sphere = scene.CreateSphereGeometry(1f, 48, 32);

            Material sunMaterial = scene.CreateMaterial(MaterialOptions.Basic(Colors.Yellow) with
            {
                Emissive = new Vector3(1f, 0.72f, 0.2f),
                EmissiveIntensity = 3f,
            });
            Node sun = scene.AddMesh(sphere, sunMaterial, name: "sun");
            scene.AddLight(Light.Point(new Vector3(1f, 0.9f, 0.75f), 90f, range: 80f), sun);

            List<(Node Pivot, float Speed)> orbits = [];
            (float Distance, float Radius, float Speed, uint Color)[] planets =
            [
                (3.0f, 0.28f, 1.2f, 0xB08D6A),
                (4.6f, 0.42f, 0.8f, 0x4F8FE5),
                (6.4f, 0.34f, 0.55f, 0xC1572F),
                (9.0f, 0.85f, 0.3f, 0xD9B27C),
            ];

            foreach ((float distance, float radius, float speed, uint color) in planets)
            {
                Node pivot = scene.CreateNode();
                Material material = scene.CreateMaterial(MaterialOptions.Pbr(MathHelpers.FromHex(color), 0.1f, 0.6f));
                Node planet = scene.AddMesh(sphere, material, pivot);
                planet.Position = new Vector3(distance, 0f, 0f);
                planet.Scale = new Vector3(radius);
                orbits.Add((pivot, speed));
            }

            Node camera = scene.AddCamera(Camera.Perspective(50f.ToRadians(), 0.1f, 500f), new Vector3(0f, 12f, 20f));
            camera.LookAt(Vector3.Zero);

            float time = 0f;
            AppWindow window = new(WindowOptions.Default with
            {
                Title = "Solar system",
                Renderer = RendererOptions.Default with { Bloom = true, BloomIntensity = 0.6f },
            });
            window.Render += (renderer, delta) =>
            {
                time += delta;
                foreach ((Node pivot, float speed) in orbits)
                {
                    pivot.EulerAngles = new Vector3(0f, time * speed * 0.4f, 0f);
                }

                renderer.Render(scene, camera);
            };
            window.Run();
            """),

        new ProjectTemplate(
            "terrain",
            "Procedural terrain",
            "Simulation",
            "A height field generated with value noise, rebuilt into a mesh at startup.",
            """
            // Generated by Three.Net App Generator (Jack - The Code Bender).

            using System.Numerics;
            using ThreeNet;
            using ThreeNet.Interop;

            const int resolution = 160;
            const float size = 40f;

            using Scene scene = new()
            {
                Environment = SceneEnvironment.Default with
                {
                    Background = MathHelpers.FromHex(0x0C1017),
                    FogColor = new Vector3(0.05f, 0.07f, 0.10f),
                    FogDensity = 0.02f,
                    FogStart = 12f,
                    AmbientIntensity = 0.1f,
                },
            };

            Vertex[] vertices = new Vertex[resolution * resolution];
            List<uint> indices = new((resolution - 1) * (resolution - 1) * 6);
            float step = size / (resolution - 1);

            for (int z = 0; z < resolution; z++)
            {
                for (int x = 0; x < resolution; x++)
                {
                    float px = (x * step) - (size * 0.5f);
                    float pz = (z * step) - (size * 0.5f);
                    float height = Fbm(px * 0.08f, pz * 0.08f) * 4.5f;
                    vertices[(z * resolution) + x] = new Vertex(
                        new Vector3(px, height, pz),
                        Vector3.UnitY,
                        new Vector2(x / (float)(resolution - 1), z / (float)(resolution - 1)));
                }
            }

            for (int z = 0; z < resolution - 1; z++)
            {
                for (int x = 0; x < resolution - 1; x++)
                {
                    uint a = (uint)((z * resolution) + x);
                    uint b = a + 1;
                    uint c = a + resolution;
                    uint d = c + 1;
                    indices.AddRange([a, c, b, b, c, d]);
                }
            }

            Geometry terrain = scene.CreateGeometry(vertices, [.. indices]);
            terrain.ComputeNormals();

            Material material = scene.CreateMaterial(MaterialOptions.Pbr(MathHelpers.FromHex(0x4E7A4A), 0f, 0.85f));
            scene.AddMesh(terrain, material, name: "terrain");

            Node sun = scene.AddLight(Light.Directional(new Vector3(1f, 0.94f, 0.85f), 3f));
            sun.Position = new Vector3(20f, 25f, 10f);
            sun.LookAt(Vector3.Zero);

            Node camera = scene.AddCamera(Camera.Perspective(55f.ToRadians(), 0.1f, 300f), new Vector3(0f, 12f, 26f));
            camera.LookAt(Vector3.Zero);

            AppWindow window = new(WindowOptions.Default with { Title = "Procedural terrain" });
            window.Render += (renderer, delta) => renderer.Render(scene, camera);
            window.Run();

            // Fractal value noise: four octaves of a smooth hash.
            static float Fbm(float x, float y)
            {
                float total = 0f;
                float amplitude = 1f;
                float frequency = 1f;
                for (int octave = 0; octave < 4; octave++)
                {
                    total += Noise(x * frequency, y * frequency) * amplitude;
                    amplitude *= 0.5f;
                    frequency *= 2f;
                }

                return total;
            }

            static float Noise(float x, float y)
            {
                int xi = (int)MathF.Floor(x);
                int yi = (int)MathF.Floor(y);
                float xf = x - xi;
                float yf = y - yi;
                float u = xf * xf * (3f - (2f * xf));
                float v = yf * yf * (3f - (2f * yf));

                float n00 = Hash(xi, yi);
                float n10 = Hash(xi + 1, yi);
                float n01 = Hash(xi, yi + 1);
                float n11 = Hash(xi + 1, yi + 1);

                return float.Lerp(float.Lerp(n00, n10, u), float.Lerp(n01, n11, u), v);
            }

            static float Hash(int x, int y)
            {
                int h = (x * 374761393) + (y * 668265263);
                h = (h ^ (h >> 13)) * 1274126177;
                return ((h ^ (h >> 16)) & 0xFFFF) / 32768f - 1f;
            }
            """),

        new ProjectTemplate(
            "game-runner",
            "Endless runner game",
            "Game",
            "Keyboard controlled player, scrolling obstacles and collision detection.",
            """
            // Generated by Three.Net App Generator (Jack - The Code Bender).

            using System.Numerics;
            using ThreeNet;

            using Scene scene = new()
            {
                Environment = SceneEnvironment.Default with { AmbientIntensity = 0.15f },
            };

            Geometry cube = scene.CreateBoxGeometry(1f, 1f, 1f);
            Material playerMaterial = scene.CreateMaterial(MaterialOptions.Pbr(Colors.Cyan, 0.2f, 0.3f));
            Material obstacleMaterial = scene.CreateMaterial(MaterialOptions.Pbr(Colors.Red, 0.1f, 0.5f));
            Material floorMaterial = scene.CreateMaterial(MaterialOptions.Pbr(MathHelpers.FromHex(0x232936), 0f, 0.9f));

            Node floor = scene.AddMesh(scene.CreatePlaneGeometry(12f, 240f), floorMaterial, name: "floor");
            floor.EulerAngles = new Vector3(-MathF.PI / 2f, 0f, 0f);
            floor.Position = new Vector3(0f, -0.5f, -100f);

            Node player = scene.AddMesh(cube, playerMaterial, name: "player");

            Random random = new();
            List<Node> obstacles = [];
            for (int i = 0; i < 20; i++)
            {
                Node obstacle = scene.AddMesh(cube, obstacleMaterial, name: $"obstacle {i}");
                obstacle.Position = new Vector3((random.NextSingle() * 8f) - 4f, 0f, -10f - (i * 9f));
                obstacles.Add(obstacle);
            }

            Node sun = scene.AddLight(Light.Directional(Vector3.One, 3f));
            sun.Position = new Vector3(4f, 8f, 4f);
            sun.LookAt(Vector3.Zero);

            Node camera = scene.AddCamera(Camera.Perspective(60f.ToRadians()), new Vector3(0f, 3.5f, 8f));
            camera.LookAt(new Vector3(0f, 0f, -6f));

            float input = 0f;
            float speed = 14f;
            float score = 0f;
            bool alive = true;

            AppWindow window = new(WindowOptions.Default with { Title = "Runner" });
            window.Input += (renderer, e) =>
            {
                if (e.Kind == InputEventKind.KeyDown)
                {
                    if (e.Key is Key.Left or Key.A) input = -1f;
                    if (e.Key is Key.Right or Key.D) input = 1f;
                    if (e.Key == Key.Escape) Environment.Exit(0);
                }
                else if (e.Kind == InputEventKind.KeyUp && e.Key is Key.Left or Key.Right or Key.A or Key.D)
                {
                    input = 0f;
                }
            };

            window.Render += (renderer, delta) =>
            {
                if (alive)
                {
                    score += delta * 10f;
                    speed += delta * 0.35f;

                    Vector3 position = player.Position;
                    position.X = Math.Clamp(position.X + (input * 9f * delta), -5f, 5f);
                    player.Position = position;
                    player.EulerAngles = new Vector3(0f, 0f, -input * 0.4f);

                    foreach (Node obstacle in obstacles)
                    {
                        Vector3 p = obstacle.Position;
                        p.Z += speed * delta;
                        if (p.Z > 6f)
                        {
                            p.Z -= 20f * 9f;
                            p.X = (random.NextSingle() * 8f) - 4f;
                        }

                        obstacle.Position = p;

                        // Axis aligned overlap is enough for unit cubes.
                        if (MathF.Abs(p.Z - player.Position.Z) < 1f && MathF.Abs(p.X - player.Position.X) < 1f)
                        {
                            alive = false;
                            Console.WriteLine($"Game over. Score: {score:F0}");
                        }
                    }
                }

                renderer.Render(scene, camera);
            };
            window.Run();
            """),

        new ProjectTemplate(
            "particle-lab",
            "Particle lab",
            "Visual effects",
            "Hundreds of emissive particles with HDR bloom and additive motion.",
            """
            // Generated by Three.Net App Generator (Jack - The Code Bender).

            using System.Numerics;
            using ThreeNet;

            const int particleCount = 600;

            using Scene scene = new()
            {
                Environment = SceneEnvironment.Default with
                {
                    Background = MathHelpers.FromHex(0x03040A),
                    AmbientIntensity = 0.01f,
                },
            };

            Geometry sphere = scene.CreateSphereGeometry(0.08f, 12, 8);
            Material[] palette =
            [
                Emissive(scene, 0xFF7A18),
                Emissive(scene, 0x4FD1E5),
                Emissive(scene, 0xB14EFF),
                Emissive(scene, 0x30D158),
            ];

            Random random = new(11);
            List<(Node Node, Vector3 Velocity)> particles = [];
            for (int i = 0; i < particleCount; i++)
            {
                Node node = scene.AddMesh(sphere, palette[i % palette.Length]);
                node.Position = RandomVector(random, 6f);
                particles.Add((node, RandomVector(random, 1.5f)));
            }

            Node camera = scene.AddCamera(Camera.Perspective(55f.ToRadians()), new Vector3(0f, 0f, 16f));
            camera.LookAt(Vector3.Zero);

            AppWindow window = new(WindowOptions.Default with
            {
                Title = "Particle lab",
                Renderer = RendererOptions.Default with
                {
                    Bloom = true,
                    BloomIntensity = 1.1f,
                    BloomThreshold = 0.9f,
                    ToneMapping = ToneMapping.Aces,
                },
            });

            window.Render += (renderer, delta) =>
            {
                for (int i = 0; i < particles.Count; i++)
                {
                    (Node node, Vector3 velocity) = particles[i];
                    Vector3 position = node.Position + (velocity * delta);

                    // Pull every particle back towards the origin: a soft attractor.
                    Vector3 pull = -position * 0.25f * delta;
                    velocity += pull;

                    node.Position = position;
                    particles[i] = (node, velocity);
                }

                renderer.Render(scene, camera);
            };
            window.Run();

            static Material Emissive(Scene scene, uint hex)
            {
                Vector4 color = MathHelpers.FromHex(hex);
                return scene.CreateMaterial(MaterialOptions.Basic(color) with
                {
                    Emissive = new Vector3(color.X, color.Y, color.Z),
                    EmissiveIntensity = 5f,
                });
            }

            static Vector3 RandomVector(Random random, float scale) => new(
                (random.NextSingle() - 0.5f) * scale,
                (random.NextSingle() - 0.5f) * scale,
                (random.NextSingle() - 0.5f) * scale);
            """),

        new ProjectTemplate(
            "simulator",
            "Bouncing ball simulator",
            "Simulation",
            "Gravity, restitution and wall collisions on a set of spheres.",
            """
            // Generated by Three.Net App Generator (Jack - The Code Bender).

            using System.Numerics;
            using ThreeNet;

            const float gravity = -9.81f;
            const float restitution = 0.82f;
            const float bounds = 6f;
            const float radius = 0.5f;

            using Scene scene = new()
            {
                Environment = SceneEnvironment.Default with { AmbientIntensity = 0.12f },
            };

            Geometry sphere = scene.CreateSphereGeometry(radius, 32, 24);
            Material floorMaterial = scene.CreateMaterial(MaterialOptions.Pbr(MathHelpers.FromHex(0x262B36), 0f, 0.9f));
            Node floor = scene.AddMesh(scene.CreatePlaneGeometry(bounds * 2f, bounds * 2f), floorMaterial, name: "floor");
            floor.EulerAngles = new Vector3(-MathF.PI / 2f, 0f, 0f);

            Random random = new(3);
            List<(Node Node, Vector3 Velocity)> balls = [];
            for (int i = 0; i < 12; i++)
            {
                Material material = scene.CreateMaterial(MaterialOptions.Pbr(
                    MathHelpers.FromHex((uint)random.Next(0x333333, 0xFFFFFF)), 0.3f, 0.25f));
                Node node = scene.AddMesh(sphere, material, name: $"ball {i}");
                node.Position = new Vector3(
                    (random.NextSingle() - 0.5f) * bounds,
                    2f + (random.NextSingle() * 4f),
                    (random.NextSingle() - 0.5f) * bounds);
                balls.Add((node, new Vector3((random.NextSingle() - 0.5f) * 4f, 0f, (random.NextSingle() - 0.5f) * 4f)));
            }

            Node sun = scene.AddLight(Light.Directional(Vector3.One, 3f));
            sun.Position = new Vector3(6f, 10f, 6f);
            sun.LookAt(Vector3.Zero);

            Node camera = scene.AddCamera(Camera.Perspective(55f.ToRadians()), new Vector3(0f, 6f, 14f));
            camera.LookAt(new Vector3(0f, 1.5f, 0f));

            AppWindow window = new(WindowOptions.Default with { Title = "Bouncing balls" });
            window.Render += (renderer, delta) =>
            {
                // Clamp the step so a stalled frame cannot tunnel a ball through the floor.
                float step = MathF.Min(delta, 1f / 30f);

                for (int i = 0; i < balls.Count; i++)
                {
                    (Node node, Vector3 velocity) = balls[i];
                    velocity.Y += gravity * step;
                    Vector3 position = node.Position + (velocity * step);

                    if (position.Y < radius)
                    {
                        position.Y = radius;
                        velocity.Y = -velocity.Y * restitution;
                    }

                    if (MathF.Abs(position.X) > bounds - radius)
                    {
                        position.X = MathF.CopySign(bounds - radius, position.X);
                        velocity.X = -velocity.X * restitution;
                    }

                    if (MathF.Abs(position.Z) > bounds - radius)
                    {
                        position.Z = MathF.CopySign(bounds - radius, position.Z);
                        velocity.Z = -velocity.Z * restitution;
                    }

                    node.Position = position;
                    balls[i] = (node, velocity);
                }

                renderer.Render(scene, camera);
            };
            window.Run();
            """),

        new ProjectTemplate(
            "product-viewer",
            "Product viewer (Avalonia)",
            "Application",
            "An Avalonia window embedding the 3D view, with orbit controls and a material panel.",
            """
            // Generated by Three.Net App Generator (Jack - The Code Bender).
            // Avalonia host: the 3D view is a normal control in the layout.

            using System.Numerics;
            using Avalonia;
            using Avalonia.Controls;
            using Avalonia.Layout;
            using Avalonia.Media;
            using Avalonia.Themes.Fluent;
            using ThreeNet;
            using ThreeNet.Avalonia;

            internal static class Program
            {
                [STAThread]
                public static void Main(string[] args) => AppBuilder.Configure<ViewerApp>()
                    .UsePlatformDetect()
                    .StartWithClassicDesktopLifetime(args);
            }

            internal sealed class ViewerApp : Application
            {
                public override void Initialize() => Styles.Add(new FluentTheme());

                public override void OnFrameworkInitializationCompleted()
                {
                    Scene scene = BuildScene(out Node camera);

                    ThreeNetView view = new()
                    {
                        Scene = scene,
                        Camera = camera,
                        RendererOptions = RendererOptions.Default with { MsaaSamples = 4, BgraOutput = true },
                    };

                    OrbitController orbit = new(view, camera) { AutoRotate = true, AutoRotateSpeed = 0.25f };
                    orbit.FrameBounds(scene.GetBounds());

                    Slider roughness = new() { Minimum = 0.05, Maximum = 1, Value = 0.35, Width = 180 };
                    Material material = scene.FindByName("product")!.Scene.CreateMaterial(MaterialOptions.Pbr(Colors.Orange));
                    roughness.PropertyChanged += (_, e) =>
                    {
                        if (e.Property == RangeBase.ValueProperty)
                        {
                            material.Update(options => options with { Roughness = (float)roughness.Value });
                        }
                    };

                    StackPanel controls = new()
                    {
                        Orientation = Orientation.Horizontal,
                        Spacing = 12,
                        Margin = new Thickness(16),
                        Children =
                        {
                            new TextBlock { Text = "Roughness", VerticalAlignment = VerticalAlignment.Center },
                            roughness,
                        },
                    };

                    Grid root = new() { RowDefinitions = new RowDefinitions("*,Auto") };
                    root.Children.Add(view);
                    Grid.SetRow(controls, 1);
                    root.Children.Add(controls);

                    if (ApplicationLifetime is Avalonia.Controls.ApplicationLifetimes.IClassicDesktopStyleApplicationLifetime desktop)
                    {
                        desktop.MainWindow = new Window
                        {
                            Title = "Product viewer",
                            Width = 1100,
                            Height = 720,
                            Background = new SolidColorBrush(Color.FromRgb(10, 12, 18)),
                            Content = root,
                        };
                    }

                    base.OnFrameworkInitializationCompleted();
                }

                private static Scene BuildScene(out Node camera)
                {
                    Scene scene = new();
                    Material material = scene.CreateMaterial(MaterialOptions.Pbr(Colors.Orange, 0.4f, 0.35f));
                    Node product = scene.AddMesh(scene.CreateTorusGeometry(1.1f, 0.38f, 24, 96), material, name: "product");
                    product.EulerAngles = new Vector3(0.5f, 0f, 0f);

                    Node key = scene.AddLight(Light.Directional(Vector3.One, 3f));
                    key.Position = new Vector3(4f, 6f, 5f);
                    key.LookAt(Vector3.Zero);

                    Node fill = scene.AddLight(Light.Point(new Vector3(0.4f, 0.6f, 1f), 30f, range: 20f));
                    fill.Position = new Vector3(-5f, 2f, 3f);

                    camera = scene.AddCamera(Camera.Perspective(45f.ToRadians()), new Vector3(0f, 1f, 6f));
                    camera.LookAt(Vector3.Zero);
                    return scene;
                }
            }
            """,
            UsesAvalonia: true),
    ];
}
