using System.Numerics;
using ThreeNet.Interop;

namespace ThreeNet;

/// <summary>Kind of input event raised by the window loop.</summary>
public enum InputEventKind : uint
{
    Resized = 0,
    KeyDown = 1,
    KeyUp = 2,
    MouseDown = 3,
    MouseUp = 4,
    MouseMove = 5,
    MouseWheel = 6,
    TouchBegin = 7,
    TouchMove = 8,
    TouchEnd = 9,
    Focus = 10,
    CloseRequested = 11,
    ScaleFactorChanged = 12,
}

/// <summary>
/// Platform independent key codes. The values mirror
/// <c>threenet_core::window::Key</c> and must stay in sync with it.
/// </summary>
public enum Key : uint
{
    Unknown = 0,
    A = 1, B = 2, C = 3, D = 4, E = 5, F = 6, G = 7, H = 8, I = 9, J = 10, K = 11, L = 12, M = 13,
    N = 14, O = 15, P = 16, Q = 17, R = 18, S = 19, T = 20, U = 21, V = 22, W = 23, X = 24, Y = 25, Z = 26,
    Digit0 = 27, Digit1 = 28, Digit2 = 29, Digit3 = 30, Digit4 = 31,
    Digit5 = 32, Digit6 = 33, Digit7 = 34, Digit8 = 35, Digit9 = 36,
    Escape = 37, Enter = 38, Space = 39, Tab = 40, Backspace = 41, Delete = 42, Insert = 43,
    Left = 44, Right = 45, Up = 46, Down = 47,
    Home = 48, End = 49, PageUp = 50, PageDown = 51,
    ShiftLeft = 52, ShiftRight = 53, ControlLeft = 54, ControlRight = 55,
    AltLeft = 56, AltRight = 57, SuperLeft = 58, SuperRight = 59,
    F1 = 60, F2 = 61, F3 = 62, F4 = 63, F5 = 64, F6 = 65,
    F7 = 66, F8 = 67, F9 = 68, F10 = 69, F11 = 70, F12 = 71,
    Minus = 72, Equal = 73, BracketLeft = 74, BracketRight = 75, Backslash = 76,
    Semicolon = 77, Quote = 78, Comma = 79, Period = 80, Slash = 81, Backquote = 82,
    NumPad0 = 83, NumPad1 = 84, NumPad2 = 85, NumPad3 = 86, NumPad4 = 87,
    NumPad5 = 88, NumPad6 = 89, NumPad7 = 90, NumPad8 = 91, NumPad9 = 92,
    NumPadAdd = 93, NumPadSubtract = 94, NumPadMultiply = 95, NumPadDivide = 96, NumPadEnter = 97,
}

/// <summary>Mouse buttons, ordered as the native layer reports them.</summary>
public enum MouseButton : uint
{
    Left = 0,
    Right = 1,
    Middle = 2,
    Back = 3,
    Forward = 4,
}

/// <summary>Keyboard modifier flags.</summary>
[Flags]
public enum KeyModifiers : uint
{
    None = 0,
    Shift = 1,
    Control = 2,
    Alt = 4,
    Super = 8,
}

/// <summary>A window or input event. Which fields matter depends on <see cref="Kind"/>.</summary>
public readonly struct InputEvent
{
    internal InputEvent(in NativeInputEvent native)
    {
        Kind = (InputEventKind)native.Kind;
        RawCode = native.Code;
        Modifiers = (KeyModifiers)native.Modifiers;
        Position = new Vector2(native.X, native.Y);
        Delta = new Vector2(native.DeltaX, native.DeltaY);
        IsRepeat = native.Repeat != 0;
    }

    public InputEventKind Kind { get; }

    /// <summary>Key code, mouse button index or touch id, depending on the kind.</summary>
    public uint RawCode { get; }

    public KeyModifiers Modifiers { get; }

    /// <summary>Cursor position, or the new size for <see cref="InputEventKind.Resized"/>.</summary>
    public Vector2 Position { get; }

    /// <summary>Movement delta, or the wheel delta in lines.</summary>
    public Vector2 Delta { get; }

    /// <summary>True when a key event was generated by auto-repeat.</summary>
    public bool IsRepeat { get; }

    /// <summary>The key for keyboard events.</summary>
    public Key Key => Kind is InputEventKind.KeyDown or InputEventKind.KeyUp ? (Key)RawCode : Key.Unknown;

    /// <summary>The button for mouse button events.</summary>
    public MouseButton Button => (MouseButton)RawCode;

    /// <summary>New size in pixels for <see cref="InputEventKind.Resized"/>.</summary>
    public (int Width, int Height) Size => ((int)Position.X, (int)Position.Y);

    /// <summary>True when the window gained focus (<see cref="InputEventKind.Focus"/>).</summary>
    public bool IsFocused => RawCode != 0;

    public override string ToString() => Kind switch
    {
        InputEventKind.KeyDown or InputEventKind.KeyUp => $"{Kind}({Key}, {Modifiers})",
        InputEventKind.MouseDown or InputEventKind.MouseUp => $"{Kind}({Button} at {Position})",
        InputEventKind.MouseMove => $"MouseMove({Position}, delta {Delta})",
        InputEventKind.MouseWheel => $"MouseWheel({Delta})",
        InputEventKind.Resized => $"Resized({Size.Width}x{Size.Height})",
        _ => Kind.ToString(),
    };
}
